<?php
/**
 * Plugin Name: ME-SIM Bridge
 * Description: Puente seguro de comunicación entre api.me-sim.com y me-sim-com-weld.vercel.app. Gestiona CORS, redirecciones 301 y webhook HMAC.
 * Version: 2.0.0
 * Author: Generated by NotebookLM
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

// ==========================================
// CONFIGURACIÓN DE CONSTANTES (AJUSTA AQUÍ)
// ==========================================
if ( ! defined( 'ME_SIM_NEXTJS_WEBHOOK_URL' ) ) {
    define( 'ME_SIM_NEXTJS_WEBHOOK_URL', 'https://me-sim.com/api/v1/woocommerce-webhook' );
}

if ( ! defined( 'ME_SIM_BRIDGE_SECRET' ) ) {
    define( 'ME_SIM_BRIDGE_SECRET', 'Este_2026_Clem_y_yo_nos_vamos_a_forrar!' ); // Debe coincidir con ME_SIM_BRIDGE_SECRET en tu .env de Next.js
}

if ( ! defined( 'ME_SIM_FRONTEND_URL' ) ) {
    define( 'ME_SIM_FRONTEND_URL', 'https://me-sim.com' );
}

// ==========================================
// 1. CONTROL DE CORS Y CREDENCIALES
// ==========================================
add_action( 'init', 'me_sim_handle_cors' );
function me_sim_handle_cors() {
    $origin = get_http_origin();
    $allowed_origins = array(
        'https://me-sim-com-weld.vercel.app',
        'http://localhost:3000',
        'http://api.me-sim.com',
        'https://me-sim.com',
        'https://www.me-sim.com',
        'https://me-sim.es',
        'https://www.me-sim.es'
                
    );

    if ( in_array( $origin, $allowed_origins ) ) {
        header( 'Access-Control-Allow-Origin: ' . $origin );
        header( 'Access-Control-Allow-Credentials: true' );
        header( 'Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE' );
        header( 'Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, X-ME-SIM-Signature' );
        
        if ( $_SERVER['REQUEST_METHOD'] == 'OPTIONS' ) {
            status_header( 200 );
            exit;
        }
    }
}

// ==========================================
// 2. REDIRECCIONES 301 PARA OCULTAR BACKEND
// ==========================================
add_action( 'template_redirect', 'me_sim_redirect_clean' );
function me_sim_redirect_clean() {
    if ( is_cart() ) {
        wp_redirect( ME_SIM_FRONTEND_URL . '/cart', 301 );
        exit;
    }
    if ( is_checkout() ) {
        wp_redirect( ME_SIM_FRONTEND_URL . '/checkout', 301 );
        exit;
    }
    if ( is_account_page() ) {
        wp_redirect( ME_SIM_FRONTEND_URL . '/login', 301 );
        exit;
    }
    if ( is_shop() ) {
        wp_redirect( ME_SIM_FRONTEND_URL, 301 );
        exit;
    }
}

// ==========================================
// 3. WEBHOOK CON FIRMA HMAC AL COMPLETAR PEDIDO
// ==========================================
add_action( 'woocommerce_order_status_completed', 'me_sim_notify_order_completed', 10, 1 );
function me_sim_notify_order_completed( $order_id ) {
    $order = wc_get_order( $order_id );
    if ( ! $order ) {
        return;
    }

    $customer_email = $order->get_billing_email();
    $customer_first_name = $order->get_billing_first_name();
    $customer_last_name = $order->get_billing_last_name();
    $customer_name = trim( $customer_first_name . ' ' . $customer_last_name );

    $items = array();
    $first_sku = '';
    
    foreach ( $order->get_items() as $item_id => $item ) {
        $product = $item->get_product();
        $sku = $product ? $product->get_sku() : '';

        // ARQUITECTURA API-DRIVEN: Si el SKU tradicional de WooCommerce está vacío,
        // extraemos el SKU/Plan ID de los metadatos que nuestro Next.js envía al crear el pedido
        if ( empty( $sku ) ) {
            $possible_meta_keys = array( 'plan_id', '_plan_id', 'sku', '_sku', 'plan_code', 'planCode' );
            foreach ( $possible_meta_keys as $key ) {
                $meta_val = $item->get_meta( $key );
                if ( ! empty( $meta_val ) ) {
                    $sku = $meta_val;
                    break;
                }
            }
        }

        if ( empty( $first_sku ) && ! empty( $sku ) ) {
            $first_sku = $sku;
        }

        $items[] = array(
            'product_id' => $item->get_product_id(),
            'name'       => $item->get_name(),
            'quantity'   => $item->get_quantity(),
            'total'      => $item->get_total(),
            'sku'        => $sku,
        );
    }

    $payload = array(
        'order_id'      => $order_id,
        'email'         => $customer_email,
        'customerName'  => $customer_name,
        'sku'           => $first_sku, // SKU simplificado al primer nivel para acceso rápido en Next.js
        'items'         => $items,
        'currency'      => $order->get_currency(),
        'total_amount'  => $order->get_total(),
        'timestamp'     => time(),
    );

    $payload_json = json_encode( $payload );
    $signature = hash_hmac( 'sha256', $payload_json, ME_SIM_BRIDGE_SECRET );

    // Enviar el webhook síncronamente
    $response = wp_safe_remote_post( ME_SIM_NEXTJS_WEBHOOK_URL, array(
        'headers' => array(
            'Content-Type'         => 'application/json',
            'X-ME-SIM-Signature'   => $signature,
        ),
        'body'    => $payload_json,
        'timeout' => 15,
        'blocking' => true,
    ));

    $logger = wc_get_logger();
    $log_context = array( 'source' => 'me-sim-bridge' );

    if ( is_wp_error( $response ) ) {
        $logger->error( 'Fallo crítico al notificar a Next.js de la Orden #' . $order_id . ': ' . $response->get_error_message(), $log_context );
    } else {
        $status_code = wp_remote_retrieve_response_code( $response );
        $response_body = wp_remote_retrieve_body( $response );
        if ( $status_code === 200 || $status_code === 201 ) {
            $logger->info( 'Orden #' . $order_id . ' transferida con éxito al backend de Next.js para su aprovisionamiento.', $log_context );
        } else {
            $logger->error( 'Error de backend Next.js para Orden #' . $order_id . ' (Código HTTP ' . $status_code . '): ' . $response_body, $log_context );
        }
    }
}

// ==========================================
// 4. INTERCEPTAR EMAILS Y CORREGIR URLS (WP_MAIL)
// ==========================================
add_filter( 'wp_mail', 'me_sim_bridge_filter_outgoing_mail_urls' );
function me_sim_bridge_filter_outgoing_mail_urls( $args ) {
    if ( isset( $args['message'] ) ) {
        // Reemplazar el subdominio del backend de la API por el dominio público de Next.js
        $args['message'] = str_replace( 'https://api.me-sim.com', 'https://me-sim.com', $args['message'] );
        $args['message'] = str_replace( 'api.me-sim.com', 'me-sim.com', $args['message'] );
    }
    return $args;
}
